### ISSUE TITLE
Renaming of the Ontology editor/Questionnaires

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#106]
1) In the drop-down list that appears when clicked on “System”, “Questionnaires” should be changed to “Data Hierarchy Editor”.

2) In the Ontology editor window:
![Screenshot from 2023-10-25 14-04-44](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/08dfaafe-65a7-461e-a6ec-e6e6df2e7bf6)
- The title of the window “Ontology Editor” should be changed to “Data Hierarchy Editor” .
- The phrase “Edit questionnaires” → “Edit the data hierarchy for the PASTA-ELN projects”.
-  “Data Type” stays the same.
- In the editing field “Enter iri for the type” change to “Enter the IRI for the type”.
- For the “Structure level 1” and “Structure level 2”, change the “Tasks” label to “Folders”.

3) Property categories and property table:
![Screenshot from 2023-10-25 14-07-15](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/b2e4e897-88d9-4ffb-a9b1-f6201df14e93)
- Instead of “Property category”, use “Metadata Group”.
- The title of the table “Properties” → “Metadata Form Editor”.
- Add a description below the table title: “Edit the metadata form for the selected data type.”.
- Inside the table:
    - “List”→” Drop-down list”
    - “Required”→ “Mandatory” or “Mandatory field”
- The button “Add property” should be changed to “Add metadata group”.

3) “Show/hide Attachments”  button remains the same.

4) “Create new type” window:
![Screenshot from 2023-10-25 14-08-54](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/a871024e-b19d-44a5-84cf-5ca72ed08e7e)
- “Enter Type title” → “ Title in the hierarchy” and “Enter the Data Type title for the hierarchy”
- “Enter Type Label” → “Displayed title” and ”Enter the displayed title of the Data Type”.

_Enhancement suggestion: in the “Create new type” window, there should be an option to select an icon for the data type (if not structural) instead of the default asterisk._

5)  If the hints that appear when hovering over editable fields contain the namings that will be changed according to the suggestions in this issue, please change those as well.

### _Discussion points_

- Should I remove ontology term from everywhere? All the files have a ontology, prefix..should they all be adjusted to data hierarchy?
  - _Yes_
- Adding combo-box for the list column in metadata group table need more effort and can be addressed itself as a separate issue? I have to do a spike to see if this is possible at all..Is this really required?
  - _This is not needed, the request was to modify the column header name (list) alone. "List" would be sufficient_
- How the required metadata for "-tags" and "-name" be populated? Will they have to be part of every metadata group or should be present in any of the group? Can they be present separately in any of the group or have to be together in a particular group? Presently the "mandatory field" is set to true by default for the metadata representing "-name" & "-tags", is this the expected way or can they be simply set to false?
  - _name can be mandatory, tags not mandatory. Just make sure that the default group always contains name and tags_
- Do the '-name' column to be unique across all metadata groups or have to be only unique within just a group?
  - _every items in metadata table for a specific type has to be unique across all groups for the "name" column property_
- What about the attachments, they have to be also checked for empty rows? Any changes to be done for the terminology?
  - _No change_
- Enhancement suggestion from Hanna: in the “Create new type” window, there should be an option to select an icon for the data type (if not structural) instead of the default asterisk. What is this icon for? "Select an icon" means to select from a pre-populated list? Should there be an additional combobox/list to be added to the UI for the icon property?
  - _Address this as part of different issue_
- How to rename the sections and subsections in [help page](https://pasta-eln.github.io/pasta-eln/ontology_configuration.html)
  - _change ontology to data hierarchy everywhere_
- IRI in meta table should display the lookup all the item, not just during the double click
  - _This needs more effort and can be addressed as a separate issue_

**Comment by jmurugan-fzj** [comment]
@HTsybenko Hanna, could you please also suggest the changes needed in [help page](https://pasta-eln.github.io/pasta-eln/ontology_configuration.html) too? Since we change the terminologies used in tool, I think the help page also needs to be adapted!

**Comment by HTsybenko** [comment]
@jmurugan-fzj I agree that the help page should be adapted correspondingly. You can use the original post as a translation dictionary and update all the terms on the help page that need to be changed. I will check it afterwards to see if everything makes sense.

The same applies to hints that appear when hovering over different fields in the editor; I mentioned it in (5).

**Comment by SteffenBrinckmann** [comment]
My branch should be ready for this change, we have to address a few issues
@jmurugan-fzj 
- we call the database property now dataHierarchy as in ontology_configuration_extended.py:438
- I need to know the new class name in ontology_configuration_extended.py, 'OntologyConfigurationForm' becomes what? and what is this file-path going to be.

I guess these are the only two items that we have to coordinate.

**Comment by SteffenBrinckmann** [comment]
my branch is sb_renameOntology

**Comment by jmurugan-fzj** [comment]
> My branch should be ready for this change, we have to address a few issues @jmurugan-fzj
> 
> * we call the database property now dataHierarchy as in ontology_configuration_extended.py:438
> * I need to know the new class name in ontology_configuration_extended.py, 'OntologyConfigurationForm' becomes what? and what is this file-path going to be.
> 
> I guess these are the only two items that we have to coordinate.

@HTsybenko @SteffenBrinckmann I have a few more points also to be discussed along with the ones mentioned above, see them below please:

- Should I remove ontology term from everywhere? All the files have a ontology, prefix..should they all be adjusted to data hierarchy?
- Adding combo-box for the list column in metadata group table need more effort and can be addressed itself as a separate issue? I have to do a spike to see if this is possible at all..Is this really required?
- How the mandatory -tags and -name be populated? Will they have to be part of every metadata group or should be present in any of the group? Can they be present separately in any of the group or have to be together in a particular group?
- Do the '-name' column to be unique across all metadata groups or have to be only unique within just a group?
What about the attachments, they have to be also checked for empty rows? Any changes to be done for the terminology?
- Enhancement suggestion from Hanna: in the “Create new type” window, there should be an option to select an icon for the data type (if not structural) instead of the default asterisk. What is this icon for? "Select an icon" means to select from a pre-populated list? Should there be an additional combobox/list to be added to the UI for the icon property?
- How to rename the sections and subsections in [help page](https://pasta-eln.github.io/pasta-eln/ontology_configuration.html)

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann Most of the changes suggested by @HTsybenko has been integrated into the branch: [feature/106-renaming-of-the-ontology-editorquestionnaires](https://github.com/PASTA-ELN/pasta-eln/tree/feature/106-renaming-of-the-ontology-editorquestionnaires). I have also made some related changes in the pasta app outside data hierarchy editor, please take a look there and we can discuss further to agree on the changes to be done for the points listed above!!

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj some comments:
- can you also rename the folder to data_hierarchy
- the files inside the folder do not need the "data_hierarchy" string in the title, since they are inside the folder, and that should be enough.
- if we include the icons-suggestion, we need to store that in the ontology
  - I would prefer to name the 'prop" -> 'meta" (that is sufficient and keeps the code somewhat shorter)
  - ontology / data hierarchy should thus be version 4
  - and it gets a new name

Let's discuss and agree on things, before we implement. I also would like to talk about the git-branch / version structure.

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj suggested changes:
Could you implement the icon & shortcut changes into the gui? 
Can you change: main editor

    "Metadata Form Editor" -> "Metadata"
    "Add metadata group" on button -> "Add metadata"
    "Create New Type" -> "Create a new data type":
    "Title in the hierarchy" -> "Data type"
    "Displayed title" -> "Title"
    "Is this a structural Type?": not needed anymore since structural levels cannot be added or deleted
    "Enter the Data type tile for the hierarchy" -> "Enter the data type"
    "Enter the displayed title of the Data Type" -> "Enter the displayed title"
    If you would like these wording changes to be a separate issue, I can do that too.

**Comment by HTsybenko** [comment]
Tooltip suggestion for the Metadata table: 
"Table which lists and allows editing of all the properties associated with the above selected type"

 -> "Table for all metadata associated with the Data Type. Add "comment" or "content" for editable text fields, "image" for image support, or enter another Data Type to enable links."

**Comment by jmurugan-fzj** [comment]
> @jmurugan-fzj suggested changes: Could you implement the icon & shortcut changes into the gui? Can you change: main editor
> 
> ```
> "Metadata Form Editor" -> "Metadata"
> "Add metadata group" on button -> "Add metadata"
> "Create New Type" -> "Create a new data type":
> "Title in the hierarchy" -> "Data type"
> "Displayed title" -> "Title"
> "Is this a structural Type?": not needed anymore since structural levels cannot be added or deleted
> "Enter the Data type tile for the hierarchy" -> "Enter the data type"
> "Enter the displayed title of the Data Type" -> "Enter the displayed title"
> If you would like these wording changes to be a separate issue, I can do that too.
> ```

@SteffenBrinckmann All the changes including the one recommended by @HTsybenko in the previous comment are integrated as part of #173

The point _**"Is this a structural Type?": not needed anymore since structural levels cannot be added or deleted**_ is not addressed yet since it will be a major change requiring changes at many places and also test suite extensively! @SteffenBrinckmann Could you please create a new issue for this one specifying the requirement what do you expect from "Create a new datatype" UI form and what not possible via for structural level types (Only x0 is possible here-after,  anything more to add)?

Also there is an additional requirement for the "icon" mentioned in the "Discussion points" (See issue description above) @SteffenBrinckmann or @HTsybenko Could one of you create a new issue with detailed requirements for introducing the icon entry!!
