### ISSUE TITLE
Changing file names

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#269]
A file's name can be changed only once through the GUI. While in the project view, the changes will be visible every time the name is edited and saved, the file itself will remain with the name assigned during the first edit.

For example, try changing the name of simple.png twice.

The names of the regular folders and the name of the project folder can be changed multiple times without issues.

**Comment by SteffenBrinckmann** [comment]
@HTsybenko I had the initial idea that one can change the name in Pasta, to make it easy to understand and use; but that the filename should not change, because the filename might have some important information: 2024_10_15_4325435.tif. Not sure how to proceed:
- allow all changes
- do nto allow changes
- save original name in separate field and allow the change

**Comment by HTsybenko** [comment]
@SteffenBrinckmann How about keeping a "Name" field that is editable only in the PASTA project and is, by default, the same as the filename and below it a "Filename" field that will be locked from editing?

I assume this is what you meant in the third option.

**Comment by SteffenBrinckmann** [comment]
@HTsybenko Yes. Then the question is, what would you like to change or is the current version working?

**Comment by HTsybenko** [comment]
@SteffenBrinckmann I uploaded the corresponding video (Issue 269) to [Sciebo](https://fz-juelich.sciebo.de/s/vWTvyh4slWePAAu).

**Comment by HTsybenko** [comment]
The issue is fixed in 2.6.0b1.

**Comment by SteffenBrinckmann** [comment]
Reopen in connection to #322

**Comment by SteffenBrinckmann** [comment]
Issue does not occur in 3.0
