### ISSUE TITLE
Project visibility issues

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#35]
Issues related to the visibility options for the projects:

- Open a project in a project view - click "visibility" button on the top right - click "hide/show hidden subitems"- the entire project disappears from GUI.
- The “hide/show entire project” option seems to not do anything.
- "Minimize-maximize subitems" option  sometimes does not work- needs to be clicked twice to minimize, clicking more to maximize does not do anything.
- All selected visibility options  except for the problematic  “hide/show hidden subitems” function only until the project is reopened. Then, the options are returned to default.

**Comment by SteffenBrinckmann** [comment]
Hey,
- there was a code change and by accident two options were intermixed, first two bullet points are due to it. 
- indeed, some visibility changes are permanent (hide/show), the rest is temporary until the view is recreated
- in addition to the intermixing, there was also another terrible mistake due to the code change.

Bugs should be repaired by #44 

If you disagree with some of the design ideas regrading visibility and their permanence, please mention them

**Comment by SteffenBrinckmann** [comment]
I have to look into 3 and into the dialog opening. The latter, I have to check on your computer.

Everything else is working as designed.
Hiding is permanent and has to be manually undone=shown
Minimizing is temporary for getting better overview.
It is obvious that we better document this

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann What is the scope of this bug fix? It's a must that we should be very specific When we close this bug, it should be clear that which all are fixed as part of this and which all are pending! If the effort is a lot, we could split this into multiple issues and address them separately...

**Comment by HTsybenko** [comment]
The visibility options seem to function at this point, and the “hide/show entire project” is not intermixed with the "hide/show hidden subitems" anymore. Therefore, I close this issue.

I still have a number of points to be discussed regarding the overall user experience with the visibility options, for which I will create a separate issue.
